### ISSUE TITLE
Chrome password-saving uses the zip-code instead of the username in the username slot

### ISSUE THREAD

**Issue by marknuzz** [TranshumanNationalCommitte/TNCVote#4]
After registering, chrome asks me if I want to save my password, and shows my username as the zip-code I entered in.

**Comment by DavidJKelley** [comment]
wow, that not seems like a bug... :)  will need to look into that for sure probably tonight...

**Comment by ggrow3** [comment]
Not sure what is meant by this... "chrome asks me if I want to save my password, and shows my username as the zip-code I entered in."  How does Chrome show the username as the zip-code? Where? Thanks.

**Comment by DavidJKelley** [comment]
we should test the login and just make sure the current hash is not the zip code going into the db... just to be sure... 

Date: Mon, 18 Jan 2016 15:09:48 -0800

**Comment by marknuzz** [comment]
@kjmnel  @DavidJKelley the zip code isn't going into the DB, this is purely a browser issue affecting the client.  

I can tell you the exact reason this is happening.  The Postal Code field comes immediately before the password field on the registration.  To fix this, simply re-order the fields (in the code) so that the password is positioned immediately after the e-mail.

You can also try setting the internal id of the Email field to "username", and that may also solve it.

![](http://ft.trillian.im/30a23cd835c1a6834bcb6c7b2740649b0f2aaf28/6EDLPWAEwBvMHvh6D004Ok3u0gT76.jpg)

**Comment by ggrow3** [comment]
Ok that makes sense.Thanks Nuzz. Much appreciated. Will try Email first and then look into adding the user name.
